### ISSUE TITLE
Problem connecting SSH to the VM

### ISSUE THREAD

**Issue by FernandoMVG** [jdposada/oop_202201#11]
According to the install doc, after I say yes, powershell should ask me about the password, but it doesn't. It's a mistake? Or is PowerShell not asking for the password? or am I confused?

![image](https://user-images.githubusercontent.com/98895066/154591800-5653d449-a50f-4d2f-bc3d-1a3923c70206.png)

**Comment by jdposada** [comment]
Hi @FernandoMVG ,

Be sure you configured your VM using a user that is actually named `azureuser`. From the message I see, it looks like you specified that the connection with your virtual machine needed a public key file instead of a username and password. Please see this [issue](https://github.com/jdposada/oop_202201/issues/5#issuecomment-1039178559) for where to change that at the moment you are creating the VM.
